### ISSUE TITLE
Highlight entire line if a change is detected

### ISSUE THREAD

**Issue by mgibbs189** [arnab/jQuery.PrettyTextDiff#10]
@arnab great work, PrettyTextDiff is awesome!

I was wondering if it's possible to shade an entire line if a change is detected on the line:

![](http://i.imgur.com/CXZ69dH.png)

Notice how the change is only visible after scrolling:

![](http://i.imgur.com/5CLhPM7.png)

Thanks for any insight!

**Comment by arnab** [comment]
Hi @mgibbs189 - thanks for the kind words.

You can use [jQuery's has selector](http://api.jquery.com/has-selector/) to look for your diff-container containing `<ins>` and `<del>` elements and style those. An example:

```
$(".diff-container:has(ins)").addClass("has-diff");
```

Does that work?

**Comment by mgibbs189** [comment]
@arnab That code snippet looks like it'd highlight the *entire* diff body, even if only 1 line contains changes. I'm trying to highlight only the actual lines with changes.

E.g. from the first screenshot, [active_plugins] is its own line, same goes for [blog_charset].

Maybe I'm over-thinking this, and it'd be best to just add `word-wrap: break-word` and call it a day :smile:

**Comment by arnab** [comment]
What I mean is this library will add `<ins>` and `<del>` into the changing containers. So if you have every line in a separate DOM element, you can use the presence of `ins/del` to detect changing lines.

Sounds like you don't though. In that case, yeah, `word-wrap` might be the answer. UX wise too, it'd probably be easier to scan when you don't have to scan at all.

**Comment by mgibbs189** [comment]
Agreed, thanks for the feedback
