### ISSUE TITLE
Is this project still maintained? Demo not working

### ISSUE THREAD

**Issue by turboteddy** [arnab/jQuery.PrettyTextDiff#18]
@arnab : The referenced [jsfiddle demo](http://jsfiddle.net/q7hyfev8/5/) on the [README.md](https://github.com/arnab/jQuery.PrettyTextDiff/blob/master/README.md) does not work - relies on [external script](http://google-diff-match-patch.googlecode.com/svn/trunk/javascript/diff_match_patch.js) that is not found (404).

**Comment by yuanrui** [comment]
In this page has demo
https://code.google.com/p/google-diff-match-patch/

**Comment by erkanarslan** [comment]
It's not working

**Comment by arnab** [comment]
There was a PR that fixed the demo: https://github.com/arnab/jQuery.PrettyTextDiff/pull/16.
