### ISSUE TITLE
the demo doesn't work

### ISSUE THREAD

**Issue by kennblvnp** [arnab/jQuery.PrettyTextDiff#19]
Thats it.

**Comment by aquadk** [comment]
Try this one. I changed the link til diff_match_patch.js.

http://jsfiddle.net/gw48xfje/2/

**Comment by dainw** [comment]
There was some malformed HTML preventing this from working - I corrected this in a new fork: 

http://jsfiddle.net/qwd923v1/

**Comment by sandeepimpressads** [comment]
Please update in documentation.

**Comment by arnab** [comment]
Sorry for the delay. There was a PR that fixed the demo: https://github.com/arnab/jQuery.PrettyTextDiff/pull/16
